version: '3.8'

services:
  web:
    build:
      context: ./web
  server:
    build:
      context: ./server
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server
      - web
    # volumes:
    # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
